name: OpenTofu Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

permissions:
  id-token: write

jobs:
  tests:
    name: Tests
    uses: osinfra-io/github-terraform-gcp-called-workflows/.github/workflows/test.yml@test
    if: github.actor != 'dependabot[bot]'
    with:
      service_account: plt-lz-testing-github@plt-lz-terraform-tf00-sb.iam.gserviceaccount.com
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
